name: CI Qt CMake

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: jurplel/install-qt-action@v3
        with:
          version: 6.7.2
      - name: Configure
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build --config Release -- -j$(nproc)
      - name: Inspect build directory
        run: |
          echo "Build (Linux) :"
          ls -R build

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jurplel/install-qt-action@v3
        with:
          version: 6.7.2
      - name: Configure
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build --config Release
      - name: Inspect build directory
        run: dir build /s

  build-macos-intel:
    runs-on: macos-15-large
    steps:
      - uses: actions/checkout@v4
      - uses: jurplel/install-qt-action@v3
        with:
          version: 6.7.2
      - name: Configure Intel
        run: cmake -B build-intel -S . -DCMAKE_BUILD_TYPE=Release
      - name: Build Intel
        run: cmake --build build-intel --config Release
      - name: Inspect build directory
        run: |
          echo "Build-intel (macOS) :"
          ls -R build-intel

  build-macos-arm:
    runs-on: macos-15-arm64
    steps:
      - uses: actions/checkout@v4
      - uses: jurplel/install-qt-action@v3
        with:
          version: 6.7.2
      - name: Configure ARM
        run: cmake -B build-arm -S . -DCMAKE_BUILD_TYPE=Release
      - name: Build ARM
        run: cmake --build build-arm --config Release
      - name: Inspect build directory
        run: |
          echo "Build-arm (macOS) :"
          ls -R build-arm
