name: Generate Doxygen documentation + publication

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Get the source code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Doxygen and Graphviz installation
      run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

    - name: Generate the documentation
      run: doxygen Doxyfile

    - name: Publish on GitHub Pages (gh-pages branch)
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc/html
